name: publish to nuget

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Wolf.Systems
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.407

    - name: Pack
      run: dotnet pack src\Wolf.Systems\Wolf.Systems.csproj --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
           dotnet pack src\Wolf.Systems.Abstracts\Wolf.Systems.Abstracts.csproj --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
           dotnet pack src\Wolf.Systems.Core\Wolf.Systems.Core.csproj --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
           dotnet pack src\Wolf.Systems.Data\Wolf.Systems.Data.csproj --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:        
        nuget-version: '5.x'

    - name: Push to Nuget
      run: nuget push src\*\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET }}
           nuget push src\*\bin\Release\*.snupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET }}
